### ISSUE TITLE
你好，10.15的系统NVIDIA显卡（DGPU）能否驱动？

### ISSUE THREAD

**Issue by VersionZKP2356** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#10]
我在网上看到有人用webdriver all versions驱动了NVIDIA的独立显卡，但是这个方法只适用于10.14，10.15亲测翻车，无法安装，请问有没有新方法？

**Comment by CerteKim** [comment]
@VersionZKP2356 
对于N卡驱动方面的事情我不太了解。

**Comment by VersionZKP2356** [comment]
好的
