### ISSUE TITLE
您好，有关cfg lock的问题

### ISSUE THREAD

**Issue by lunjielee** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#11]
您好！
请问是如何获取cfg lock的相关位置的，我的电脑型号是G3 3779, 尝试过从bios文件找可是dell的bios文件没有办法直接获取到

**Comment by asdwer440453** [comment]
我的是3779，我来回答吧，我已经测试了，和楼主的是一样的，直接启动gurb，输入给的命令就行

**Comment by lunjielee** [comment]
> 我的是3779，我来回答吧，我已经测试了，和楼主的是一样的，直接启动gurb，输入给的命令就行

的确可用, 今早已确认可行

**Comment by CerteKim** [comment]
@lunjielee 
from https://osxlatitude.com/forums/topic/10549-how-to-change-dvmt-for-dell-system/

1) 使用 Universal BIOS Backup ToolKit 2.0.exe 备份BIOS
2) 使用 UEFITool.exe to 搜索 ```899407d7-99fe-43d8-9a21-79ec328cac21``` 然后解压 PE32 body 到文件（例如：Setup.bin）
3) 使用 Universal IFR Extractor.exe to 解压 setup.bin 到文本
4) 在文本中搜索 DVMT，CFG 等

**Comment by lunjielee** [comment]
> 1. Universal BIOS Backup ToolKit 2.0.exe

感谢
