### ISSUE TITLE
关于OC引导启动Windows的问题

### ISSUE THREAD

**Issue by VersionZKP2356** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#13]
我用你的OpenCore引导启动，发现可以直接通过OC进入Windows系统，而并不需要用rEFInd，在OpenCore Boot Menu里选择Windows启动，便启动了win，没有BSOD（蓝屏），这与你在readme里写的不一样呀

**Comment by CerteKim** [comment]
@VersionZKP2356  
我习惯用 rEFInd 来作为主 Bootloader，所以并没有测试 OpenCore 是否能启动 Windows 。
许多文件被修改了，也许不小心就修好了这个问题。

**Comment by VersionZKP2356** [comment]
哦

**Comment by VersionZKP2356** [comment]
只要勾上一个booter下的quirk就可以了
