### ISSUE TITLE
CFG锁的问题

### ISSUE THREAD

**Issue by VersionZKP2356** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#14]
![image](https://user-images.githubusercontent.com/62052278/88492808-0616c180-cfe0-11ea-8c81-bb45491dc0b2.png)
我从你的config.plist中发现这两个关于CFG锁的选项都关闭了，是不是需要用你的grub来解锁CFG后再装macOS big sur？

**Comment by VersionZKP2356** [comment]
这两个选项应该没解锁CFG的都该开启吧，后面还有一个

**Comment by L0gIc301** [comment]
G3-3579 BIOS里面没找到CFG有关选项啊

**Comment by CerteKim** [comment]
@VersionZKP2356 @L0gIc301   
BIOS 里面的 CFG 是隐藏的，通过我的 grubx64.efi 可以修改。
如果不想用这种方式的话可以去修改 OpenCore 的 Quirk，这都是可以的。
