### ISSUE TITLE
DW1820a无线网卡驱动问题

### ISSUE THREAD

**Issue by VersionZKP2356** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#16]
我用你的EFI安装成功了macOS big sur，结果我的dw1820a网卡无法驱动，显示不出来（貌似显示在USB里面）蓝牙正常，怎么办
![截屏2020-07-27 15 57 19](https://user-images.githubusercontent.com/62052278/88517742-e86a4c00-d021-11ea-8613-50a8d5cc44d4.png)
![截屏2020-07-27 15 57 32](https://user-images.githubusercontent.com/62052278/88517744-ea340f80-d021-11ea-8ec3-045bf10dcd8c.png)

**Comment by CerteKim** [comment]
@VersionZKP2356  
那你运气比我好，我现在还起不来。
至于 WIFI 的问题，可以去 config.plist 里面将  DeviceProperties 里面 DW1820A 的 compatible 改成 pci14e4,43a3

**Comment by CerteKim** [comment]
@VersionZKP2356  
我这边安装成功，但是不能启动 macOS Installer，所以没有测试 WIFI。

**Comment by VersionZKP2356** [comment]
我已经改好了，等会重启试试

**Comment by CerteKim** [comment]
@VersionZKP2356 
好的

**Comment by CerteKim** [comment]
@VersionZKP2356  
其实我很想问问有没有需要修改的地方，因为我这总是遇到奇奇怪怪的内核问题。

**Comment by VersionZKP2356** [comment]
我枯了.......依然不行，还有我这macos有点卡，打开右上角的控制中心，等标志时需要等两三秒才能出来

**Comment by VersionZKP2356** [comment]
网上说添加引导参数有个brcmfx-driver=1和brcmfix-country=#a，但是他用的是clover，我不知道可不可以，我的occ开不起来了，我等会休眠一下再唤醒试试

**Comment by CerteKim** [comment]
@VersionZKP2356  
就很迷惑
我找到起不来的原因了，我的硬盘是SM961，它不兼容 Big Sur。

**Comment by VersionZKP2356** [comment]
黑果小兵的博客里写的dw1820a的Wi-Fi需要在config里面加入网卡的pci地址，我看你的也加入了，但就是驱动不了。hackintool里面也看不见有关Wi-Fi的PCI设备，只有USB里有。

**Comment by VersionZKP2356** [comment]
只有一个Realtek的有线网卡，其他的都是Intel设备

**Comment by CerteKim** [comment]
@VersionZKP2356 
我装到机械硬盘上测试一下看看吧，SM961 这个硬盘太阴间了

**Comment by VersionZKP2356** [comment]
额，我一直都装在机械盘上，系统有点卡

**Comment by VersionZKP2356** [comment]
![截屏2020-07-28 17 14 28](https://user-images.githubusercontent.com/62052278/88644645-cfcb6600-d0f5-11ea-94a2-0de78324c97f.png)
有好多人都跟你一样

**Comment by VersionZKP2356** [comment]
我在hackintool里都看不到无线网卡，并且bcm4350在big sur中不能用了，所以我怀疑是不是因为我屏蔽了无线网卡的金属触点导致的，我先试试加引导参数

**Comment by CerteKim** [comment]
@VersionZKP2356  
试试看吧，我这好像也这样了

**Comment by VersionZKP2356** [comment]
金属触点已经取消屏蔽了，但是依然没用，hackintool里看不到啊，我怀疑是不是big sur不支持，但黑果小兵都可以

**Comment by VersionZKP2356** [comment]
真不行我再换回Intel网卡，用itlwm驱动吧

**Comment by VersionZKP2356** [comment]
我认为应该把deviceproperties里的WLAN的选项给删掉。黑果小兵上说的只有在无法驱动时才添加那个选项，如果不添加就能正常运行就不添加

**Comment by VersionZKP2356** [comment]
没用啊，PCI里还看不到无线网卡

**Comment by CerteKim** [comment]
@VersionZKP2356  试试我最新的更新吧，我这好像可以

**Comment by VersionZKP2356** [comment]
我用10.13.6了，我感觉11卡，黒果小兵已经有解决方案了
要加brcmfx-aspm这个引导参数

**Comment by VersionZKP2356** [comment]
反正我也就用10.13.6吧，真佩服oc的兼容性，0.6.0可以引导13，0.0.4可以引导15.4
