### ISSUE TITLE
Can't boot into installer (bigsur branch)

### ISSUE THREAD

**Issue by jerrybeomsoo** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#17]
Hello, I installed bigsur branch Opencore bootloader onto my ssd's EFI system partition. However, I can't get into the installer because of some error. I did not modify any of the provided files, and my laptop spec is the same as the readme.md except for the WiFi (DW1560 instead of DW1820A) and SSD (Samsung 970 EVO).

Below image is the log when I tried to boot Big Sur beta installer.
![IMG_20200727_233943](https://user-images.githubusercontent.com/18094442/88555922-5e42d780-d063-11ea-84d2-83015e84f89f.jpg)

Thanks in advance!

**Comment by VersionZKP2356** [comment]
cfg锁你关了没

**Comment by VersionZKP2356** [comment]
This OC boot can only boot MacOS on devices that have closed the CFG lock. If you do not, please close it or turn on the three quirks about CFG lock

**Comment by VersionZKP2356** [comment]
Hope to help you.

**Comment by jerrybeomsoo** [comment]
> Hope to help you.

Thanks. CFG lock has worked.
