### ISSUE TITLE
Unable to access windows system

### ISSUE THREAD

**Issue by asdwer440453** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#2]
Hello, I have a question to ask, there is no problem for my oc to open the mac system, but at startup, if you choose the win system, you can jump to the win startup interface and turn around, but the circle gets stuck for a while and cannot be entered. How to solve it? I guess it should be the problem of BOOTx64.efi, but after I replace it, there is a new problem, that is, the startup page cannot be selected, can you help solve it?

**Comment by CerteKim** [comment]
OpenCore can boot windows by **using BootCamp**.
Here is a sample:
https://osy.gitbook.io/hac-mini-guide/installation-guide/boot-camp

For my personal preference, I used [**rEFInd Boot Manager**](http://www.rodsbooks.com/refind/) to boot other bootloaders like GRUB, OpenCore etc.
