### ISSUE TITLE
type-c驱动问题

### ISSUE THREAD

**Issue by kayeung** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#20]
你好，我的配置跟您的一模一样，我现在在自己弄oc，可是我的type-c驱动不起来，我看到你的驱动成功了，所以想请教一下您，除了添加IOElectrify.kext，USBInjectAll.kext，SSDT-TB3.aml，SSDT-TB3.dsl这4个文件进oc里，还需要有什么额外的操作吗？（我现在已经添加了这4个进去并修改了内核信息，但是仍然驱动不了）

**Comment by CerteKim** [comment]
使用的是哪一个branch

**Comment by kayeung** [comment]
我用的是小兵镜像里面自带的，usb-a是能用的，就type-c通电但是不能用，不能识别出来。usb3的接口插USB3的u盘只有480mbps的速度，但是插入usb3.1的移动硬盘就有5gbps

**Comment by CerteKim** [comment]
可能需要 SSDT-USBX

**Comment by kayeung** [comment]
我按照小兵的教程定制了USB，就是上面的情况，就好像没定制过一样

**Comment by Loading39** [comment]
不排除我在定制过程中有错误

**Comment by kayeung** [comment]
其实我最想问你的一点是，怎样把type-c的HDMI功能驱动起来?

**Comment by kayeung** [comment]
你好，请问如何通过type-c把核显画面显示出来？我现在type-c调通了，就差画面输出

**Comment by CerteKim** [comment]
可以参考黑果小兵的教程

**Comment by kayeung** [comment]
https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html 还是https://blog.daliansky.net/Coffee-Lake-frame-buffer-patch-and-UHD630-Coffee-Lake-ig-platform-id-data-finishing.html

**Comment by CerteKim** [comment]
前者
