### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by kayeung** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#21]
将OC文件夹放入efi，还需要其他步骤吗？（我的配置跟您的一样）grubx64.efi又是要怎么用？？

**Comment by CerteKim** [comment]
使用bios引导加载 `grubx64.efi` 然后就可以使用它的命令行来解锁 cfg lock
如果没有解锁 cfg lock 的话，要去 `config.plist` 修改相关的选项
