### ISSUE TITLE
attempting system restart

### ISSUE THREAD

**Issue by asdwer440453** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#3]
Hello, when I start the computer, the computer appears“ attempting system restart” , and then the computer restarts, i.e. it can't enter the system, and the OC can be used before. Is it related to the BIOS settings

**Comment by CerteKim** [comment]
It might related to BIOS settings, but shouldn't.
What's your hardware specs?

**Comment by Tsuitecsun** [comment]
My computer appears“ attempting system restart” too. And my computer not restart, the hareware specs is i58300H ,HD630,Sound card:Realtek ALC236
Wireless network card:Broadcom BCM94352z
Bluetooth:Broadcom BCM94352z
This install is not successful.

**Comment by CerteKim** [comment]
@Tsuitecsun @asdwer440453

I tested my EFI configuration on my friend's Dell G3 3579 with i5 8300H.

OpenCore boot from local disk by default, and it won't boot from usb media.

Enable OpenCore boot menu by follow the step below:

Edit **config.plist**

Find
```
<key>ShowPicker</key>
<false/>
```

change ```false``` to ```true```

and now you can use OpenCore to boot your installation media

**Comment by Tsuitecsun** [comment]
你好，我使用你的clover引导卡在一行+++++++++++++++++++++++号不动了，只能强制关机，怎样解决？版本号是macos14.4的，戴尔g3&nbsp; 3579，请问是国人吗？我可以换一下英语呢，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "古影曦月"<notifications@github.com&gt;; 
发送时间: 2020年2月25日(星期二) 上午7:12
收件人: "CerteKim/Dell-G3-3579-Hackintosh-OpenCore"<Dell-G3-3579-Hackintosh-OpenCore@noreply.github.com&gt;; 
抄送: "1614353590"<1614353590@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [CerteKim/Dell-G3-3579-Hackintosh-OpenCore] attempting system restart (#3)




I tested my EFI configuration on my friend's Dell G3 3579 with i5 8300H.
 
OpenCore boot from local disk by default, and it won't boot from usb media.
 
Enable OpenCore boot menu by follow the step below:
 
Edit config.plist
 
Find
 <key&gt;ShowPicker</key&gt; <false/&gt;  
change false to true
 
and now you can use OpenCore to boot your installation media

**Comment by CerteKim** [comment]
@Tsuitecsun 还是用 OpenCore 吧
