### ISSUE TITLE
Thunderbolt 3 progress

### ISSUE THREAD

**Issue by aarlin** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#4]
Hey, first off I want to give thanks for opening this repo up for us. I have the same laptop and it was super helpful to get the hackintosh running.

Did you happen to get anywhere with TB3 support? I looked around and tried messing with SSDT-TB3.aml - switching the SSDT values of RP05 to RP21 based on [the idiot's guide portion](https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/) but no luck.

**Comment by CerteKim** [comment]
I dont have TB3 device to verify if SSDT patch worked.
I'm sorry that it is not working.
