### ISSUE TITLE
About DW1820A

### ISSUE THREAD

**Issue by kayeung** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#5]
Hello,my wireless network card has replaced DW1820A.But the wifi cann't run when cold boot macos.The bluetooth is ok.If I want to run the wifi, only reboot system from windows to macos.So trouble!What's problem?How can I do it?

**Comment by kayeung** [comment]
Cannot enter the system during the first hot reboot. Stop at the Apple Logo loading interface. Only force reboot to enter the macos and run the wifi.

**Comment by CerteKim** [comment]
Maybe you should block some pin like this
![DW1820A_Cover_pins](https://user-images.githubusercontent.com/18364439/73808907-66d0f880-480c-11ea-97ff-ddf743965797.jpg)

**Comment by kayeung** [comment]
Can run in macOS10.15.3 with your OC? Are the wifi and bluetooth ok in 10.15.3??

**Comment by CerteKim** [comment]
IDK
But it works on 10.15.2

**Comment by Loading39** [comment]
I find the microphone cann't work.I cann't communicate with siri.

**Comment by kayeung** [comment]
I find the microphone don't work.I cann't communicate with siri.

**Comment by kayeung** [comment]
Inner microphone dosen't work.But my WI-1000x's microphone is ok.

**Comment by kayeung** [comment]
Now my macOS's version is 10.14.4. Can I updata system to 10.15 by ota??

**Comment by CerteKim** [comment]
Yes you can
