### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by sky2000fo** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#7]
1.直接用oc文件夹替换clover文件夹
2.是否需要有其他修改
3.有没有完整的EFI文件夹
用1方法操作后无法启动，开机显示几行代码后，自动重启进入windows系统了

**Comment by CerteKim** [comment]
我默认关闭了OpenCore的启动项菜单，你可以修改config.plist，找到
```
<key>ShowPicker</key>
<false/>
```
将```false```改成```true```。

OpenCore默认启动项是本地磁盘里面的macOS，如果你的macOS在外部磁盘（比如U盘）里面，那OpenCore并不会去启动它，而是选择Windows。

**Comment by sky2000fo** [comment]
知道了，我晚点再试下------------------ 原始邮件 ------------------
发件人: "古影曦月"<notifications@github.com>
发送时间: 2020年3月7日(星期六) 下午5:52
收件人: "CerteKim/Dell-G3-3579-Hackintosh-OpenCore"<Dell-G3-3579-Hackintosh-OpenCore@noreply.github.com>;
抄送: "sky2000fo"<1753319929@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CerteKim/Dell-G3-3579-Hackintosh-OpenCore] 如何使用 (#7)



我默认关闭了OpenCore的启动项菜单，你可以修改config.plist，找到
 <key>ShowPicker</key> <false/>  
将false改成true。
 
OpenCore默认启动项是本地磁盘里面的macOS，如果你的macOS在外部磁盘（比如U盘）里面，那OpenCore并不会去启动它，而是选择Windows。
 
&mdash;

**Comment by CerteKim** [comment]
@sky2000fo 好的
