### ISSUE TITLE
你好，可否上传bootx64.efi，试了几个文件，都无法使用

### ISSUE THREAD

**Issue by asdwer440453** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#8]
你好，可否上传boot文件夹里的bootx64.efi文件，试了几个文件，都无法使用

**Comment by CerteKim** [comment]
@asdwer440453 
我已经将bootx64.efi删除了，因为使用了rEFInd的bootx64.efi文件。
你可以直接更新OpenCore，包括其本体efi和bootx64.efi，这样也是可以使用的。
