### ISSUE TITLE
你好，请问能够取消屏蔽NVIDIA显卡吗？

### ISSUE THREAD

**Issue by VersionZKP2356** [CerteKim/Dell-G3-3579-Hackintosh-OpenCore#9]
我在网上看到有人用webdriver all versions在10.14上成功安装了NVIDIA webdriver，我也成功了，但是cuda里显示GPU not found，我想应该是n卡被屏蔽了。能否取消屏蔽NVIDIA显卡吗？

**Comment by VersionZKP2356** [comment]
是不是删除acpi文件夹下的ssdt-disable-dgpu.aml文件就可以取消屏蔽了？

**Comment by CerteKim** [comment]
@VersionZKP2356  
是的

**Comment by VersionZKP2356** [comment]
我已经学会了，在config.plist里把disable-dgpu设成false就可以了。
